### ISSUE TITLE
Weekly Scrum - Nov 24

### ISSUE THREAD

**Issue by Zhangjason308** [Zhangjason308/SYSC-4806-Project#67]
Weekly Updates for Week 2 of Milestone 2

**Comment by Zhangjason308** [comment]
### Jason

**This Week**
- Finished the Register and Profile pages and update it with mounting logic. Add memberships to User profiles
- Fix routing issue and controller inconsistencies (Issue #38 )
- Add unit and integration tests (Issue #61 )
- Setup the H2 Database and deployment of frontend and backend

**Next Week**
- Migrate the Membership to the actual membership entity instead of just a string
- Add encryption to the user login info to be stored in a hash
- Add more test cases

**Blockers**
- No blockers

**Comment by Triguy12** [comment]
This week: 
- Finalized the perk manager and controller class. 
- Finalized test cases

Next week:
- Clean up overall display
- Ensure perk manager is updated to work with future iterations
- Add sort feature

**Comment by Waluiyeegi** [comment]
Caleb

This Week

-     Finish the work on displaying the perk and making sure that it is displayed properly on the home page

-     Finish integration tests for Perk manager controller and unit tests for Perk manager.

-    Finished Readme

Next Week

- Work on Delete Perk Functionality

Blockers

    Other Assignments
